blank_issues_enabled: false
contact_links:
  - name: PingFederate Community
    url: https://support.pingidentity.com/s/topic/0TO1W000000Q9o7WAC/pingfederate
    about: Ask a question or start a discussion with the PingFederate community.
  - name: Ping DevOps Community
    url: https://support.pingidentity.com/s/topic/0TO1W000000IF30WAG/pingdevops
    about: Ask a question or start a discussion with the DevOps community.
  - name: Ping Identity Support Portal
    url: https://support.pingidentity.com/s/
    about: Visit the Ping Identity Support portal for issues not related to the PingFederate Terraform provider.
